import React from 'react'
import properties from '../../data/properties.json'
import { useRouter } from "next/router";
import Head from 'next/head';
import Link from 'next/link';
import PropertyList from '@/components/PropertyList';
import Nav from '@/components/Nav';



function Place() {
  const r = useRouter();
  return (
    <div>
        <Head>
          <title>Dhalem | Listings in {r.query?.place}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <main className='max-w-7xl mx-auto py-16 px-5'>
          <div className='space-y-5 mb-12 md:mb-16'>
            <h2 className='text-4xl font-semibold text-[#333333] tracking-wide capitalize text-center'>
              Our Listings In <span className='font-bold'>{r.query?.place}</span>
            </h2>
            <p className='text-center text-[#666666] tracking-wide leading-7'>
              Find Your Dream House And <Link href="/contact" className='underline'>Contact Us</Link> Today!!, Or <Link href="/" className='underline'>Search Again</Link>
            </p>
          </div>
          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-x-4 gap-y-10'>
            {properties.hits.map(property => (
              <Link href={`/property/${property.externalID}`} key={property.id} className='hover:scale-105 transition-all duration-200 fade-in-out'>
                <PropertyList property={property}/>
              </Link>
            ))}

          </div>
        </main>
    </div>
  )
}


export default Place