import Footer from '@/components/Footer'
import Nav from '@/components/Nav'
import React from 'react'
import Head from 'next/head'

function contact() {
  return (
    <div>
      <Head>
        <title>Dhalem | Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className='max-w-7xl mx-auto px-5 py-16'>
        <div className='space-y-5 mb-12 md:mb-16'>
            <h2 className='text-4xl font-semibold text-[#333333] tracking-wide capitalize text-center'>
              Contact Us
            </h2>
            <p className='text-center text-[#666666] tracking-wide leading-7'>
              Bring Your Family's Happiness to Your Dream House
            </p>
         </div>
         <div className='grid grid-cols-1 md:grid-cols-3 gap-x-10 gap-y-5'>
            <div className='md:col-span-2 space-y-5'>
              
            </div>
         </div>
      </main>
      <Footer />
    </div>
  )
}

export default contact