import FeaturedListing from '@/components/Home/FeaturedListing'
import Hero from '@/components/Home/Hero'
import Nav from '@/components/Nav'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className='max-w-7xl mx-auto px-5'>
        <Hero />
        <FeaturedListing />
      </main>
    </>
  )
}

